# Generated by Django 4.2 on 2024-07-05 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 22, 39, 41, 299091, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
