# Generated by Django 4.2 on 2024-07-06 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_user_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 2, 19, 54, 610127, tzinfo=datetime.timezone.utc), verbose_name='Caducidad'),
        ),
    ]
